### ISSUE TITLE
Can't launch the app on Windows 10 with the .msi

### ISSUE THREAD

**Issue by thomasbnt** [Sonar-team/Sonar_desktop_app#18]
Hello! 
I installed with the `.msi` script install, and when I would like to open the app, I've got this error.

![image](https://github.com/Sonar-team/Sonar_desktop_app/assets/14293805/86e49905-9a72-44c5-b71d-0407f7207d43)

> Impossible d'exécuter le code, car packet.dll est introuvable.
La réinstallation du programme peut corriger ce problème.

**Comment by Akmot9** [comment]
To proceed, it's necessary to install Wireshark along with WinPcap, as this process will also install the required DLL. Should this method not yield the desired result, consider manually installing the packet library using the Pnet documentation. For guidance on managing Windows dependencies, please consult the following link: [https://crates.io/crates/pnet](https://crates.io/crates/pnet).
